support offset commit store offset and messageId in pulsar
paashzj/kafka_go_pulsar pull request #26
Opened 2022-03-18 10:09 UTC by tyluffy

2022-03-18 11:49 UTC, goflutterjava commented on pkg/kafsar/offset_manager_impl.go
> +		logrus.Errorf("convert msg to bytes failed. topic: %s, err: %s", topic, err)
```suggestion
		logrus.Errorf("convert msg to bytes failed. kafka topic: %s, err: %s", topic, err)
```

2022-03-18 11:50 UTC, goflutterjava commented on pkg/kafsar/offset_manager_impl.go
> +				Errorf("send pulsar error. key: %s, err: %s", key, err)
we should print offset and kafka topic to help locate problem

2022-03-18 11:50 UTC, goflutterjava commented on pkg/kafsar/offset_manager_impl.go
> +// acquireOffset topic is kafka topic
maybe we should name params to kafkaTopic ?

2022-03-19 03:45 UTC, Shoothzj commented on pkg/kafsar/offset_manager_impl.go
> +// commitOffset topic is kafka topic
since we already named kafkaTopic, I suggest remove this annotation

2022-03-19 03:45 UTC, Shoothzj commented on pkg/kafsar/offset_manager_impl.go
> +					logrus.Errorf("consumer is closed.")
```suggestion
					logrus.Errorf("consumer already closed.")
```

2022-03-19 03:47 UTC, Shoothzj commented on pkg/constant/const.go
> +	ConsumerClosed = "consumer closed"
go only have package name, may be `ErrorMsgConsumerClosed` is better?
Anyway, we shouldn't put errorMsg and url const in same const group

2022-03-19 03:47 UTC, Shoothzj commented on pkg/kafsar/offset_manager_impl.go
> +type OffsetManagerImpl struct {
offsetManager should have a close method to cleanup resources

2022-03-19 07:36 UTC, Shoothzj commented on pkg/test/interate_offset_manage_test.go
> +	assert.Equal(t, acquireOffset.Offset, offset)
could you please add test for RemoveOffset?

2022-03-19 07:39 UTC, Shoothzj commented on pkg/kafsar/offset_manager_impl.go
> +func NewOffsetManage(producer pulsar.Producer, consumer pulsar.Consumer) OffsetManager {
```suggestion
func NewOffsetManager(producer pulsar.Producer, consumer pulsar.Consumer) OffsetManager {
```

2022-03-19 08:38 UTC, goflutterjava approved these changes

2022-03-19 08:46 UTC, Shoothzj commented on pkg/test/interate_offset_manage_test.go
> +// Licensed to the Apache Software Foundation (ASF) under one
typo integrate

2022-03-19 08:46 UTC, Shoothzj commented on pkg/test/interate_offset_manage_test.go
> +func TestOffsetManage(t *testing.T) {
```suggestion
func TestOffsetManager(t *testing.T) {
```

2022-03-19 09:54 UTC, Shoothzj commented on pkg/kafsar/kafsar.go
> +		SubscriptionName: constant.OffsetCommitName,
subscriptionName should be unique for every instance

2022-03-19 09:54 UTC, Shoothzj commented on pkg/kafsar/kafsar.go
> +		Type:             pulsar.Shared,
FailOver is better than shared

2022-03-19 10:23 UTC, Shoothzj requested changes

2022-03-19 10:23 UTC, Shoothzj commented on pkg/kafsar/offset_manager_impl.go
> +		return MessageIdPair{}, false
are we really need MessageIdPair return?

2022-03-19 10:23 UTC, Shoothzj commented on pkg/test/integrate_offset_manager_test.go
> +	manage := kafsar.NewOffsetManager(offsetProducer, offsetConsumer)
manager

2022-03-19 11:57 UTC, merged